"""created chunks

Revision ID: 3ee3c270d2c3
Revises:
Create Date: 2026-06-06 20:53:07.044192

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "3ee3c270d2c3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
