"""changing vector column in Embedding table

Revision ID: 49515a1fc02d
Revises: 5ead58e39909
Create Date: 2026-06-09 22:52:13.460249

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49515a1fc02d"
down_revision: Union[str, Sequence[str], None] = "5ead58e39909"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embeddings", "embedding_vector")

    # 2. Add it fresh as a pgvector column
    op.add_column(
        "embeddings",
        sa.Column("embedding_vector", pgvector.sqlalchemy.Vector(384), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("embeddings", "embedding_vector")
    op.add_column("embeddings", sa.Column("embedding_vector", sa.JSON(), nullable=True))
    # ### end Alembic commands ###
