"""add chunk_tsvector

Revision ID: ac1aec0d8776
Revises: 49515a1fc02d
Create Date: 2026-07-16 00:03:26.842347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = "ac1aec0d8776"
down_revision: Union[str, Sequence[str], None] = "49515a1fc02d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chunks", sa.Column("chunk_tsvector", postgresql.TSVECTOR(), nullable=True)
    )
    op.execute("UPDATE chunks SET chunk_tsvector = to_tsvector('english', chunk_text)")
    op.create_index(
        "ix_chunks_tsvector",
        "chunks",
        ["chunk_tsvector"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "embeddings",
        "embedding_vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "embedding_vector",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
        nullable=True,
    )
    op.drop_index("ix_chunks_tsvector", table_name="chunks", postgresql_using="gin")
    op.drop_column("chunks", "chunk_tsvector")
    # ### end Alembic commands ###
